<?php
/**
 * Dashboard.
 *
 * @copyright André Schöne
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Dashboard
 * @author André Schöne <andre.schoene@onlinehome.de>.
 * @link http://www.schoenes-neue-welt.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Jun 07 13:38:24 CEST 2012.
 */

/**
 * Check permissions during the workflow.
 *
 * @param array $obj
 * @param int $permLevel
 * @param int $currentUser
 * @return bool
 */
function Dashboard_workflow_simpleapproval_permissioncheck($obj, $permLevel, $currentUser)
{
    /** TODO */
    $component = 'Dashboard::';
    // process $obj and calculate an instance
    /** TODO */
    $instance = '::';

    return SecurityUtil::checkPermission($component, $instance, $permLevel, $currentUser);
}
