<?php
/**
 * Dashboard.
 *
 * @copyright André Schöne
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Dashboard
 * @author André Schöne <andre.schoene@onlinehome.de>.
 * @link http://www.schoenes-neue-welt.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Jun 07 13:38:24 CEST 2012.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for boxx entities.
 */
class Dashboard_Entity_Validator_Boxx extends Dashboard_Entity_Validator_Base_Boxx
{
    // here you can add custom validation methods or override existing checks
}
