<?php
/**
 * Dashboard.
 *
 * @copyright André Schöne
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Dashboard
 * @author André Schöne <andre.schoene@onlinehome.de>.
 * @link http://www.schoenes-neue-welt.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu May 03 12:43:34 CEST 2012.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for plugins entities.
 */
class Dashboard_Entity_Validator_Base_Plugins extends Dashboard_Validator
{

    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('Dashboard');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('active')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('active'), $dom);
            return $errorInfo;
        }
        //if (!$this->isNumberNotEmpty('active')) {
        //    $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('active'), $dom);
        //    return $errorInfo;
        //}
        //if (!$this->isNumberNotLongerThan('active', 11)) {
        //    $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('active', 11), $dom);
        //    return $errorInfo;
        //}
        if (!$this->isStringNotLongerThan('name', 30)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('name', 30), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('name')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('name'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 250)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 250), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('dbsize')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('dbsize'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('dbsize')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('dbsize'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('dbsize', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('dbsize', 11), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('dbfile', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('dbfile', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('dbfile')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('dbfile'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('ajax')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('ajax'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('ajax')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('ajax'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('ajax', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('ajax', 11), $dom);
            return $errorInfo;
        }
        return true;
    }

    /**
     * Check for unique values.
     *
     * This method determines if there already exist plugins with the same plugins.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given plugins does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if (empty($this->entity[$fieldName])) {
            return false;
        }

        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository('Dashboard_Entity_Plugins');

        $excludeid = $this->entity['id'];
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }

    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }

}
