<?php
/**
 * Dashboard.
 *
 * @copyright André Schöne
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Dashboard
 * @author André Schöne <andre.schoene@onlinehome.de>.
 * @link http://www.schoenes-neue-welt.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu May 03 12:43:34 CEST 2012.
 */

/**
 * This handler class handles the page events of the Form called by the Dashboard_user_edit() function.
 * It collects common functionality required by different object types.
 */
class Dashboard_Form_Handler_User_Edit extends Dashboard_Form_Handler_User_Base_Edit
{
    // feel free to extend the base handler class here
}
